// Generated by Vial Keymap C Editor (https://vial-keymap-c-editor.pages.dev)

#include QMK_KEYBOARD_H

#ifdef QMK_SETTINGS
#include "qmk_settings.h"
#endif

/* USER INCLUDE BEGIN *//* USER INCLUDE END */

/* GENERATED CODE BEGIN */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
              KC_ESCAPE,           KC_F1,           KC_F2,           KC_F3,
                  KC_F4,           KC_F5,       KC_DELETE,           KC_F6,
                  KC_F7,           KC_F8,           KC_F9,          KC_F10,
                 KC_F11,          KC_F12,           TG(1),        KC_GRAVE,
                   KC_1,            KC_2,            KC_3,            KC_4,
                   KC_5,    KC_BACKSPACE,            KC_6,            KC_7,
                   KC_8,            KC_9,            KC_0, KC_LEFT_BRACKET,
        KC_RIGHT_BRACKET,   KC_CALCULATOR,          KC_TAB,        KC_QUOTE,
               KC_COMMA,          KC_DOT,            KC_P,            KC_Y,
                   KC_F,            KC_G,            KC_C,            KC_R,
                   KC_L,        KC_SLASH,        KC_EQUAL,         KC_MAIL,
          KC_LEFT_SHIFT,            KC_A,            KC_O,            KC_E,
                   KC_U,            KC_I,        KC_ENTER,            KC_D,
                   KC_H,            KC_T,            KC_N,            KC_S,
               KC_MINUS,  KC_RIGHT_SHIFT,    KC_CAPS_LOCK,    KC_SEMICOLON,
                   KC_Q,            KC_J,            KC_K,            KC_X,
                   KC_B,            KC_M,            KC_W,            KC_V,
                   KC_Z,    KC_BACKSLASH,     KC_WWW_HOME,    KC_LEFT_CTRL,
         (QK_LGUI|KC_X),  (QK_LGUI|KC_C),  (QK_LGUI|KC_V),        KC_SPACE,
           KC_RIGHT_GUI,         KC_HOME,           KC_UP,          KC_END,
          KC_RIGHT_CTRL,      KC_PAGE_UP,           MO(1),     KC_LEFT_GUI,
            KC_LEFT_ALT,    KC_RIGHT_ALT,         KC_LEFT,         KC_DOWN,
               KC_RIGHT,    KC_PAGE_DOWN
    ),
    [1] = LAYOUT(
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,       KC_INSERT,  KC_TRANSPARENT,
            KC_KB_POWER, KC_SYSTEM_SLEEP,  KC_SYSTEM_WAKE, KC_PRINT_SCREEN,
         KC_SCROLL_LOCK,        KC_PAUSE,  KC_TRANSPARENT,  KC_TRANSPARENT,
          QK_BOOTLOADER,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT, KC_AUDIO_VOL_UP,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,        KC_EQUAL,
            KC_KP_SLASH,  KC_KP_ASTERISK,     KC_KP_MINUS, (QK_LSFT|KC_TAB),
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT, KC_AUDIO_VOL_DOWN,         KC_HOME,
                  KC_UP,          KC_END,         KC_KP_7,         KC_KP_8,
                KC_KP_9,      KC_KP_PLUS,        KC_CLEAR,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
                KC_LEFT,         KC_DOWN,        KC_RIGHT,         KC_KP_4,
                KC_KP_5,         KC_KP_6,    KC_BACKSPACE,  KC_TRANSPARENT,
         (QK_LCTL|KC_X),  (QK_LCTL|KC_C),  (QK_LCTL|KC_V),   KC_AUDIO_MUTE,
        KC_MEDIA_PREV_TRACK,         KC_KP_1,         KC_KP_2,         KC_KP_3,
            KC_KP_ENTER,     KC_WWW_BACK,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT, KC_MEDIA_NEXT_TRACK,         KC_KP_0,  KC_TRANSPARENT,
              KC_KP_DOT,  KC_WWW_FORWARD
    ),
    [2] = LAYOUT(
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT
    ),
    [3] = LAYOUT(
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,  KC_TRANSPARENT,
         KC_TRANSPARENT,  KC_TRANSPARENT
    )
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
};
#endif

// Tap Dance definitions
#define TAP_DANCE_ENTRY(onTap, onHold, onDoubleTap, onTapHold, tappingTerm) ((vial_tap_dance_entry_t){.on_tap = onTap, .on_hold = onHold, .on_double_tap = onDoubleTap, .on_tap_hold = onTapHold, .custom_tapping_term = tappingTerm})
#if VIAL_TAP_DANCE_ENTRIES > 0
const vial_tap_dance_entry_t default_tap_dance_entries[] = {
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200),
    TAP_DANCE_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, 200)
};
#endif

// Combo definitions
#define COMBO_ENTRY(k1, k2, k3, k4, result) ((vial_combo_entry_t){.input ={k1, k2, k3, k4}, .output = result})
#if VIAL_COMBO_ENTRIES > 0
const vial_combo_entry_t PROGMEM default_combo_entries[] = {
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    COMBO_ENTRY(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
#endif

// Macro buffer
const uint8_t PROGMEM default_macro_buffer[] = {
    
};

// Key Override definitions
#if VIAL_KEY_OVERRIDE_ENTRIES > 0
const vial_key_override_entry_t default_key_override_entries[] = {
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    },
    {
        KC_NO, // trigger key
        KC_NO, // replacement key
        0xffff, // layer mask
        0, // trigger mods
        0, // negative mod mask
        0, // suppressed mods
        0 // options
    }
};
#endif

// Initialize Vial dynamic items
void __real_dynamic_keymap_reset(void);
void __wrap_dynamic_keymap_reset(void) {
    __real_dynamic_keymap_reset();

#if VIAL_TAP_DANCE_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_tap_dance_entries) / sizeof(default_tap_dance_entries[0]); ++i) {
        dynamic_keymap_set_tap_dance(i, &default_tap_dance_entries[i]);
    }
#endif
#if VIAL_COMBO_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_combo_entries) / sizeof(default_combo_entries[0]); ++i) {
        dynamic_keymap_set_combo(i, &default_combo_entries[i]);
    }
#endif
#if VIAL_KEY_OVERRIDE_ENTRIES > 0
    for (size_t i = 0; i < sizeof(default_key_override_entries) / sizeof(default_key_override_entries[0]); ++i) {
        dynamic_keymap_set_key_override(i, &default_key_override_entries[i]);
    }
#endif
#ifdef QMK_SETTINGS
    qmk_settings_t qs;
    uint8_t* p_qs = (uint8_t*)&qs;
    for (size_t i = 0; i < sizeof(qs); ++i) {
        p_qs[i] = dynamic_keymap_get_qmk_settings(i);
    }
    #ifdef VIAL_DEFAULT_TAPPING
        qs.tapping = VIAL_DEFAULT_TAPPING;
    #endif
    #ifdef VIAL_DEFAULT_AUTO_SHIFT
        qs.auto_shift = VIAL_DEFAULT_AUTO_SHIFT;
    #endif
    #ifdef DEFAULT_GRAVE_ESC_OVERRIDE
        qs.grave_esc_override = DEFAULT_GRAVE_ESC_OVERRIDE;
    #endif

    for (size_t i = 0; i < sizeof(qs); ++i) {
        dynamic_keymap_set_qmk_settings(i, p_qs[i]);
    }

    #ifdef DEFAULT_KEYMAP_EECONFIG
        keymap_config.raw = DEFAULT_KEYMAP_EECONFIG;
        eeconfig_update_keymap(keymap_config.raw);
    #endif

    qmk_settings_init();
#endif 

    uint16_t const macro_buffer_size = MIN(sizeof(default_macro_buffer), dynamic_keymap_macro_get_buffer_size());
    dynamic_keymap_macro_set_buffer(0, macro_buffer_size, (uint8_t *)default_macro_buffer);
}

/* GENERATED CODE END */


/* USER CODE BEGIN *//* USER CODE END */